import { AnyDatabaseItem } from './types'

// Datos de ejemplo
export const initialItems: AnyDatabaseItem[] = [
	{
		id: 1,
		name: 'Modern React Best Practices',
		tags: ['React', 'Frontend'],
		url: 'https://react.dev/blog/2023/03/16/introducing-react-dev',
		type: 'Link',
		usageProbability: 'High',
		createdAt: '2024-01-23',
		notes: 'Important updates about React documentation',
	},
	{
		id: 2,
		name: 'Next.js App Router Migration',
		tags: ['Next.js', 'Frontend'],
		url: 'https://nextjs.org/docs/app',
		type: 'Link',
		usageProbability: 'Medium',
		createdAt: '2024-01-22',
		notes: 'Guide for migrating to the new App Router',
	},
	{
		id: 3,
		name: 'TypeScript Advanced Patterns',
		tags: ['TypeScript', 'Backend'],
		url: 'https://www.typescriptlang.org/docs/handbook/advanced-types.html',
		type: 'Link',
		usageProbability: 'Medium',
		createdAt: '2024-01-21',
		notes: 'Deep dive into advanced TypeScript features',
	},
	{
		id: 4,
		name: 'AI Integration for Content Recommendations',
		tags: ['AI', 'ML', 'Frontend'],
		type: 'Idea',
		usageProbability: 'High',
		createdAt: '2024-01-20',
		notes:
			'Research how to integrate AI models for personalized content recommendations',
	},
	{
		id: 5,
		name: 'Database Optimization Strategies',
		tags: ['Database', 'Performance', 'Backend'],
		type: 'Note',
		usageProbability: 'Medium',
		createdAt: '2024-01-19',
		notes: 'Notes from the database optimization workshop',
	},
	{
		id: 6,
		name: 'User Authentication Flow Design',
		tags: ['Security', 'UX', 'Frontend'],
		type: 'Idea',
		usageProbability: 'High',
		createdAt: '2024-01-18',
		notes: 'Ideas for improving the user authentication experience',
	},
	{
		id: 7,
		name: 'Mobile Responsive Design Patterns',
		tags: ['CSS', 'Mobile', 'Frontend'],
		url: 'https://web.dev/articles/responsive-web-design-basics',
		type: 'Link',
		usageProbability: 'Low',
		createdAt: '2024-01-17',
		notes: 'Collection of responsive design patterns for mobile interfaces',
	},
	{
		id: 8,
		name: 'GraphQL vs REST API Comparison',
		tags: ['API', 'GraphQL', 'REST'],
		type: 'Note',
		usageProbability: 'Medium',
		createdAt: '2024-01-16',
		notes: 'Comparison of GraphQL and REST approaches for API design',
	},
]
